// Generated by https://quicktype.io

export interface Estacion {
  id:         number;
  nombre:     string;
  frecuencia: number;
  premium:    boolean;
  valoracion: number;
  alt_img?:   string;
  fecha:      string;
}
